install.packages(
  c('data.table',
    'DBI',
    'dplyr',
    'plyr',
    'reshape2',
    'RH2',
    'RJDBC',
    'RMySQL',
    'RPostgreSQL',
    'RSQLite',
    'sqldf'),
  dependencies=TRUE,
  repos='http://cran.rstudio.com')
