install.packages(c(
  'data.table',
  'DBI',
  'dplyr',
  'reshape2',
  'RH2',
  'RJDBC',
  'RMySQL',
  'RPostgreSQL',
  'RSQLite',
  'sqldf'),
  dependencies=TRUE,
  repos='http://cran.rstudio.com')
